### ISSUE TITLE
Do you have a plan to upgrade the zipper code to PHP v8.0?

### ISSUE THREAD

**Issue by sahilr2050** [victor78/yii2-zipper#2]
Do you have a plan to upgrade the zipper code to PHP v8.0?

**Comment by victor78** [comment]
@sahilr2050 Good idea, I did not think about it.
As I understand, symfony extentions, which zipper depends on, don't allow to just upgrade. Right?

**Comment by sahilr2050** [comment]
This is the error I am getting while upgrading the code to PHP v8.0

Composer code version:
```
"victor78/yii2-zipper": "^0.0.4",
```

 yii\base\ErrorException: During inheritance of ArrayAccess: Uncaught yii\base\ErrorException: Return type of Alchemy\Zippy\Adapter\AdapterContainer::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in {project_path}\vendor\alchemy\zippy\src\Adapter\AdapterContainer.php:165

```
Stack trace:
#0 {project_path}\vendor\alchemy\zippy\src\Adapter\AdapterContainer.php(28): yii\web\ErrorHandler->handleError(code: '8192', message: ''Return type of...', file: ''{project_path}...', line: '165')
#1 {project_path}\vendor\composer\ClassLoader.php(122): Composer\Autoload\ClassLoader->unknown()
#2 {project_path}\vendor\composer\ClassLoader.php(443): Composer\Autoload\ClassLoader::Composer\Autoload\{closure:{project_path}\vendor\composer\ClassLoader.php:121-123}(file: ''{project_path}...')
#3 {project_path}\vendor\victor78\zippy-ext\src\Adapter\AdapterContainer.php(29): Composer\Autoload\ClassLoader->loadClass(class: ''Alchemy\\\\Zippy...')
#4 {project_path}\vendor\composer\ClassLoader.php(122): Composer\Autoload\ClassLoader->unknown()
```

**Comment by victor78** [comment]
@sahilr2050 I got it. I'll upgrade the package in 1-2 weeks (on weekends).
